######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 8 23:46:32 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . lib
INCLUDEPATH += . lib

# Input
HEADERS += mainwin.h msort.h win.h lib/set.h lib/web.h
SOURCES += mainwin.cpp search.cpp web.cpp win.cpp
